
package ec.ups.edu.evacardenastracycli;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T11:37:07.998-05:00
 * Generated source version: 3.5.0
 *
 */
public final class LibroServiceSOAP_LibroServiceSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.EVACardenasTracySRV.edu.ups.ec/", "LibroServiceSOAPService");

    private LibroServiceSOAP_LibroServiceSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LibroServiceSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        LibroServiceSOAPService ss = new LibroServiceSOAPService(wsdlURL, SERVICE_NAME);
        LibroServiceSOAP port = ss.getLibroServiceSOAPPort();

        {
        System.out.println("Invoking crearLibro...");
        ec.ups.edu.evacardenastracycli.Libro _crearLibro_arg0 = null;
        java.lang.String _crearLibro__return = port.crearLibro(_crearLibro_arg0);
        System.out.println("crearLibro.result=" + _crearLibro__return);


        }
        {
        System.out.println("Invoking getLibros...");
        java.util.List<ec.ups.edu.evacardenastracycli.Libro> _getLibros__return = port.getLibros();
        System.out.println("getLibros.result=" + _getLibros__return);


        }

        System.exit(0);
    }

}
