package ec.ups.edu.evacardenastracycli;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T11:37:08.040-05:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://service.EVACardenasTracySRV.edu.ups.ec/", name = "LibroServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface LibroServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "crearLibro", targetNamespace = "http://service.EVACardenasTracySRV.edu.ups.ec/", className = "ec.ups.edu.evacardenastracycli.CrearLibro")
    @ResponseWrapper(localName = "crearLibroResponse", targetNamespace = "http://service.EVACardenasTracySRV.edu.ups.ec/", className = "ec.ups.edu.evacardenastracycli.CrearLibroResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearLibro(

        @WebParam(name = "arg0", targetNamespace = "")
        ec.ups.edu.evacardenastracycli.Libro arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getLibros", targetNamespace = "http://service.EVACardenasTracySRV.edu.ups.ec/", className = "ec.ups.edu.evacardenastracycli.GetLibros")
    @ResponseWrapper(localName = "getLibrosResponse", targetNamespace = "http://service.EVACardenasTracySRV.edu.ups.ec/", className = "ec.ups.edu.evacardenastracycli.GetLibrosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.ups.edu.evacardenastracycli.Libro> getLibros()
;
}
